<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var Mage_Core_Block_Template $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $this->__('Maho Installation Wizard') ?></title>
    <link rel="icon" href="<?= $this->getSkinUrl('images/favicon.svg') ?>" type="image/x-icon"/>
    <script type="text/javascript" src="<?= $jsUrl = $this->getJsUrl() ?>prototype/prototype.js"></script>
    <script type="text/javascript" src="<?= $jsUrl ?>prototype/validation.js"></script>
    <script type="text/javascript" src="<?= $jsUrl ?>scriptaculous/effects.js"></script>
    <script type="text/javascript" src="<?= $jsUrl ?>mage/translate.js"></script>
    <script type="text/javascript" src="<?= $jsUrl ?>varien/js.js"></script>
    <script type="text/javascript" src="<?= $jsUrl ?>varien/form.js"></script>
    <link rel="stylesheet" href="<?= $this->getSkinUrl('css/boxes.css') ?>" type="text/css" media="all"/>
    <link rel="stylesheet" href="<?= $this->getSkinUrl('css/clears.css') ?>" type="text/css" media="all"/>
</head>
<body>
<div class="header">
    <div class="header-top">
        <h1 id="logo">
            <a href="/">
                <img src="<?= $this->getSkinUrl('images/logo.svg') ?>" alt="<?= $this->__('Maho') ?>">
            </a>
        </h1>
    </div>
</div>
<div class="middle-container">
    <div class="middle col-2-left-layout">
        <div class="col-left side-col">
            <?= $this->getChildHtml('left') ?>
        </div>
        <div id="main" class="col-main">
            <?= $this->getChildHtml('global_messages') ?>
            <?= $this->getChildHtml('content') ?>
        </div>
    </div>
</div>
<footer>
    <?= $this->__('Help Us to Keep Maho Healthy') ?> -
    <a href="https://github.com/MahoCommerce/maho/issues"
       target="_blank"><strong><?= $this->__('Report All Bugs') ?></strong></a>
    <?= $this->__('(v%s)', Mage::getOpenMageVersion()) ?>
</footer>
</body>
</html>
