<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var Mage_Core_Block_Template $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description"
          content="robust, modern, and lean on-premise ecommerce platform for the future of your business">
    <link rel="icon" href="<?= $this->getSkinUrl('images/favicon.svg') ?>" type="image/x-icon">
    <link rel="stylesheet" href="<?= $this->getSkinUrl('css/install.css') ?>">
    <title><?= $this->__('Maho Installation Wizard') ?></title>
</head>
<body>
<header>
    <a id="logo" href="/">
        <img src="<?= $this->getSkinUrl('images/logo.svg') ?>" alt="<?= $this->__('Maho') ?>">
    </a>
    <?= $this->getChildHtml('left') ?>
</header>
<main>
    <?= $this->getChildHtml('global_messages') ?>
    <?= $this->getChildHtml('content') ?>
</main>
<footer>
    <?= $this->__('Help Us to Keep Maho Healthy') ?> -
    <a href="https://github.com/MahoCommerce/maho/issues"
       target="_blank"><strong><?= $this->__('Report All Bugs') ?></strong></a>
    <?= $this->__('(v%s)', Mage::getOpenMageVersion()) ?>
</footer>
</body>
</html>
