<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Installation start page
 *
 * @var Mage_Install_Block_Begin $this
 */
?>
<div class="page-head">
    <h3><?= $this->__("Welcome to Maho's Installation Wizard") ?>!</h3>
</div>
<?= $this->getMessagesBlock()->toHtml() ?>
<form action="<?= $this->getPostUrl() ?>" method="post">
<div style="height:20em; border:1px solid #ccc; margin-bottom:8px; padding:5px; background:#fff; overflow: auto; overflow-x:hidden; overflow-y:scroll;">
<?= $this->getLicenseHtml() ?>
</div>
    <p>
        <input type="checkbox" name="agree" value="1" id="agree" onclick="document.querySelector('#submitButton').toggleAttribute('disabled')" class="checkbox">
        <label for="agree"><?= $this->__('I agree to the above terms and conditions.') ?></label>
    </p>
    <button class="form-button" type="submit" id="submitButton" disabled><?= $this->__('Continue') ?></button>
</form>
