<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var Mage_Install_Block_Begin $this */ ?>
<h1><?= $this->__("Welcome to Maho's Installation Wizard!") ?></h1>
<?= $this->getMessagesBlock()->toHtml() ?>
<form action="<?= $this->getPostUrl() ?>" method="post">
    <section class="license">
        <cite><?= $this->getLicenseHtml() ?></cite>
    </section>
    <label>
        <input type="checkbox"
               name="agree"
               value="1"
               onclick="document.querySelector('#submitButton').toggleAttribute('disabled')">
        <?= $this->__('I agree to the above terms and conditions.') ?>
    </label>
    <button type="submit" id="submitButton" disabled><?= $this->__('Continue') ?></button>
</form>
