<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var Mage_Install_Block_State $this */ ?>

<div class="steps">
    <span class="circle active"><img src="<?= $this->getSkinUrl('images/file-signature-solid.svg') ?>" alt="Test" title="Test"></span>
    <span class="circle"><img src="<?= $this->getSkinUrl('images/location-dot-solid.svg') ?>" alt="Test"></span>
    <span class="circle"><img src="<?= $this->getSkinUrl('images/gear-solid.svg') ?>" alt="Test"></span>
    <span class="circle"><img src="<?= $this->getSkinUrl('images/user-solid.svg') ?>" alt="Test"></span>
    <span class="circle"><img src="<?= $this->getSkinUrl('images/flag-checkered-solid.svg') ?>" alt="Test"></span>
    <div class="progress-bar">
        <span class="indicator"></span>
    </div>
</div>
