<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div style="border:1px solid #ccc; background:#f6f6f6;">
    <h2 style="margin-bottom:0; border-bottom:1px solid #ccc; padding:4px 10px; color:#3c5974; font-size:1.4em;"><?= $this->__('Installation') ?></h2>
<ol style="padding:10px; border-top:1px solid #fff;">
<?php foreach ($steps as $_step): ?>
    <li <?php if ($_step->getActive()): ?>style="color:green; font-weight:bold; "<?php endif ?>><?= $this->__($_step->getCode()) ?></li>
<?php endforeach ?>
</ol>
</div>

<br/>
<p>
    <?= $this->__('Having trouble installing Maho?') ?>
    <?= $this->__('Check out our') ?> <a href="https://mahocommerce.com/getting-started" target="_blank"><?= $this->__('Installation Guide') ?></a>
</p>
