<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var Mage_Install_Block_State $this */ ?>
<h2><?= $this->__('Installation') ?></h2>
<ul>
    <?php foreach ($steps as $step): ?>
        <li <?php if ($step->getActive()): ?>class="active"<?php endif ?>><?= $this->__($step->getCode()) ?></li>
    <?php endforeach ?>
</ul>
<p>
    <?= $this->__('Having trouble installing Maho?') ?>
    <?= $this->__('Check out our') ?>
    <a href="https://mahocommerce.com/getting-started" target="_blank"><?= $this->__('Installation Guide') ?></a>
</p>
